

server:
  port: 2020


spring:
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost/spring
    username: root
    password: 4562


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true











